baseURL: http://example.org
languageCode: en-us
title: Hugo client-side search template

outputs:
  home:
    - HTML
    - RSS
    - JSON

disableKinds:
  - taxonomy
  - term

params:
  repo: https://github.com/zwbetz-gh/hugo-client-side-search-template
