baseURL: http://example.org
languageCode: en-us
title: Client-side Search for Hugo

outputs:
  home:
    - HTML
    - RSS
    - JSON

disableKinds:
  - taxonomy
  - term

params:
  repo: https://github.com/zwbetz-gh/client-side-search-for-hugo
